[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.124.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/knowledge-base.json"]
